//  This file was generated by LevelHelper
//  http://www.levelhelper.org
//
//  LevelHelperLoader.mm
//  Created by Bogdan Vladu
//  Copyright 2011 Bogdan Vladu. All rights reserved.
////////////////////////////////////////////////////////////////////////////////
//
//  This software is provided 'as-is', without any express or implied
//  warranty.  In no event will the authors be held liable for any damages
//  arising from the use of this software.
//  Permission is granted to anyone to use this software for any purpose,
//  including commercial applications, and to alter it and redistribute it
//  freely, subject to the following restrictions:
//  The origin of this software must not be misrepresented; you must not
//  claim that you wrote the original software. If you use this software
//  in a product, an acknowledgment in the product documentation would be
//  appreciated but is not required.
//  Altered source versions must be plainly marked as such, and must not be
//  misrepresented as being the original software.
//  This notice may not be removed or altered from any source distribution.
//  By "software" the author refers to this code file and not the application 
//  that was used to generate this file.
//
////////////////////////////////////////////////////////////////////////////////
#import "LHBatch.h"
#import "LHSprite.h"
#import "LHDictionaryExt.h"
#import "SHDocumentLoader.h"
#import "LHSettings.h"
//#import "LevelHelperLoader.h"


static int untitledBatchCount = 0;
////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////
@interface LHBatch (Private)
-(void)addChildFromDictionary:(NSDictionary*)childDict;
@end
////////////////////////////////////////////////////////////////////////////////
@implementation LHBatch
@synthesize uniqueName;
@synthesize imagePath;
////////////////////////////////////////////////////////////////////////////////
-(void) dealloc{		
    
  //  CCLOG(@"LH Batch Dealloc %@", uniqueName);
    
#ifndef LH_ARC_ENABLED
    [uniqueName release];
    [imagePath release];
    [shFile release];
	[super dealloc];
#endif
}
//------------------------------------------------------------------------------
-(NSString*)shFile{
    return shFile;
}
-(void)setShFile:(NSString*)file{
    
    if(file){
        if(shFile)
        {
            #ifndef LH_ARC_ENABLED
                [shFile release];
            #endif
        }
        shFile = [[NSString alloc] initWithString:file];
    }
}
//------------------------------------------------------------------------------
-(id) initWithDictionary:(NSDictionary*)dictionary layer:(LHLayer*)layer{
    
    NSString* imgPath = [[LHSettings sharedInstance] imagePath:[dictionary stringForKey:@"SheetImage"]];
    
    NSAssert(imgPath!=nil, @"Image path must not be nil");
        
    self = [super initWithFile:imgPath capacity:29]; //29 is the default capacity
    if (self != nil)
    {
        NSString* uName = [dictionary objectForKey:@"UniqueName"];
        if(uName)
            uniqueName = [[NSString alloc] initWithString:uName];
        else {
            uName = [dictionary stringForKey:@"SheetName"];
            if(uName){//we may load from SH
                uniqueName = [[NSString alloc] initWithString:uName];                
            }
            else {
                NSLog(@"ERROR - CREATING LHBatch WITH NO SHEET NAME");
                uniqueName = [[NSString alloc] initWithFormat:@"UntitledLayer_%d", untitledBatchCount];
                ++untitledBatchCount;
            }
        }
        
        if([dictionary objectForKey:@"SHScene"])
            shFile = [[NSString alloc] initWithString:[dictionary stringForKey:@"SHScene"]];
        
        imagePath = [[NSString alloc] initWithString:imgPath];
        
        zOrder_ = [dictionary intForKey:@"ZOrder"];
        
        if(layer){
            [layer addChild:self z:[self zOrder]];
        }        
    }
    return self;
}
//------------------------------------------------------------------------------
+(id) batchWithDictionary:(NSDictionary*)dictionary layer:(LHLayer*)layer{    
#ifndef LH_ARC_ENABLED
    return [[[self alloc] initWithDictionary:dictionary layer:layer] autorelease];
#else
    return [[self alloc] initWithDictionary:dictionary layer:layer];
#endif   
}
+(id) batchWithSheetName:(NSString*)sheetName shFile:(NSString*)spriteHelperFile
{
    NSDictionary* dictionary = [[SHDocumentLoader sharedInstance] dictionaryForSheetNamed:sheetName inDocument:spriteHelperFile];
    
#ifndef LH_ARC_ENABLED
    LHBatch* batch = [[[self alloc] initWithDictionary:dictionary layer:nil] autorelease];
#else
    LHBatch* batch = [[self alloc] initWithDictionary:dictionary layer:nil];
#endif       
    
    [batch setShFile:spriteHelperFile];
    return batch;
}
//------------------------------------------------------------------------------
-(void) removeSelf{
    [self removeFromParentAndCleanup:YES];
}
-(void)setParentLoader:(LevelHelperLoader*)p{
    parentLoader = p;
}
//------------------------------------------------------------------------------
-(LHSprite*)spriteWithUniqueName:(NSString*)name{
    
    for(id node in children_){
        if([node isKindOfClass:[LHSprite class]]){
            if([[(LHSprite*)node uniqueName] isEqualToString:name]){
                return node;
            }
        }
    }
    
    return nil;
}
//------------------------------------------------------------------------------
-(NSArray*)allSprites{
    NSMutableArray* array = [NSMutableArray array];
    
    for(id node in children_){
        if([node isKindOfClass:[LHSprite class]]){
            [array addObject:node];    
        }
    }
    
    return array;
}
//------------------------------------------------------------------------------
-(NSArray*)spritesWithTag:(int)tag{
    NSMutableArray* array = [NSMutableArray array];
    
    for(id node in children_){
        if([node isKindOfClass:[LHSprite class]]){
            if([(CCNode*)node tag] == tag)
                [array addObject:node];    
        }
    }
    
    return array;    
}
//------------------------------------------------------------------------------
-(void)removeFromParentAndCleanup:(BOOL)cleanup
{
   // NSLog(@"REMOVE FROM PARENT AND CLEANUP");
    [super removeFromParentAndCleanup:cleanup];
}
-(void)removeChild: (CCSprite *)sprite cleanup:(BOOL)doCleanup
{
   // NSLog(@"REMOVE CHILD CLEANUP");
	[super removeChild:sprite cleanup:doCleanup];
}

-(void)removeChildAtIndex:(NSUInteger)index cleanup:(BOOL)doCleanup
{
   // NSLog(@"REMOVE CHILD AT INDEX");
    
    [super removeChildAtIndex:index cleanup:doCleanup];
}


-(void) removeAllChildrenWithCleanup:(BOOL)cleanup
{
    //NSLog(@"BATCH REMOVE ALL CHILDRED");
    [super removeAllChildrenWithCleanup:cleanup];
}
@end
