//  This file was generated by LevelHelper
//  http://www.levelhelper.org
//
//  LevelHelperLoader.h
//  Created by Bogdan Vladu
//  Copyright 2011 Bogdan Vladu. All rights reserved.
//
////////////////////////////////////////////////////////////////////////////////
//
//  This software is provided 'as-is', without any express or implied
//  warranty.  In no event will the authors be held liable for any damages
//  arising from the use of this software.
//  Permission is granted to anyone to use this software for any purpose,
//  including commercial applications, and to alter it and redistribute it
//  freely, subject to the following restrictions:
//  The origin of this software must not be misrepresented; you must not
//  claim that you wrote the original software. If you use this software
//  in a product, an acknowledgment in the product documentation would be
//  appreciated but is not required.
//  Altered source versions must be plainly marked as such, and must not be
//  misrepresented as being the original software.
//  This notice may not be removed or altered from any source distribution.
//  By "software" the author refers to this code file and not the application 
//  that was used to generate this file.
//
////////////////////////////////////////////////////////////////////////////////

#import <Foundation/Foundation.h>
#import "cocos2d.h"
#include "Box2D.h"

#ifdef __IPHONE_OS_VERSION_MAX_ALLOWED
#import <UIKit/UIKit.h>					// Needed for UIAccelerometerDelegate
#import "CCTouchDelegateProtocol.h"		// Touches only supported on iOS
#elif defined(__MAC_OS_X_VERSION_MAX_ALLOWED)
#import "CCEventDispatcher.h"
#endif

@class LHBatch;
@class LHAnimationNode;
@class LHObserverPair;
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
#ifdef __IPHONE_OS_VERSION_MAX_ALLOWED
@interface LHSprite : CCSprite
#elif defined(__MAC_OS_X_VERSION_MAX_ALLOWED)
@interface LHSprite : CCSprite
#endif
{
	b2Body* body; //week ptr
    NSMutableArray* fixturesObj;
    NSArray* fixturesInfo; //in case we want a different scale
    
    NSMutableString* uniqueName;
    
    NSString* shSceneName;
    NSString* shSheetName;
    NSString* shSpriteName;
        
    NSString* imageFile;
    CGRect originalRect;
    
    LHAnimationNode* animation;
    
    
    CGSize realScale; //used for the joints in case you create a level with SD graphics using ipad template
            
    bool usesOverloadedTransformations; //false uses native Cocos2d setPosition setRotation - true uses LH (may cause problems in certain game logics)
    
    bool usePhysicsForTouches;
    
    id  userCustomInfo;
}
@property (readwrite) CGSize realScale;
@property (readwrite) bool swallowTouches;
////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////
//CONSTRUCTORS USED BY LEVELHELPER
//Autorelease constructors - user should almost always use this
+(id)batchSpriteWithDictionary:(NSDictionary*)dictionary batch:(LHBatch*)batch;//render by batch node
+(id)spriteWithDictionary:(NSDictionary*)dictionary;//self render

-(id)initBatchSpriteWithDictionary:(NSDictionary*)dictionary batch:(LHBatch*)batch;
-(id)initWithDictionary:(NSDictionary*)dictionary;

-(void)postInit;
//the top methods should be overloaded when overloading this class

//CONSTRUCTORS FOR THE USER
+(id)spriteWithName:(NSString*)spriteName 
          fromSheet:(NSString*)sheetName 
             SHFile:(NSString*)spriteHelperFile;

+(id)batchSpriteWithName:(NSString*)spriteName 
                   batch:(LHBatch*)batch; //necessary info is taking from the LHBatch instance



-(void)removeSelf; //use this to completely remove a sprite from the game


////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////
//INFO METHODS
//------------------------------------------------------------------------------
-(void) setUniqueName:(NSString*)name;
-(NSString*)uniqueName;

-(void) setBody:(b2Body*)body;
-(b2Body*)body;
-(bool) removeBodyFromWorld;

-(NSString*)imageFile;
-(void)setImageFile:(NSString*)img;

-(CGRect)originalRect;
-(void)setOriginalRect:(CGRect)rect;

@property (readonly) NSString* shSceneName;
@property (readonly) NSString* shSheetName;
@property (readonly) NSString* shSpriteName;
////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////
//TRANSFORMATION METHODS
//------------------------------------------------------------------------------
//The following method will transform the physic body also - if any
@property bool usesOverloadedTransformations; //use this to activate CCActions with physical sprites

-(void) transformPosition:(CGPoint)pos;
-(void) transformRotation:(float)rot;

-(void) transformScale:(float)scale;
-(void) transformScaleX:(float)scaleX;
-(void) transformScaleY:(float)scaleY;

////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////
//ANIMATION METHODS
//------------------------------------------------------------------------------
-(void) prepareAnimationNamed:(NSString*)animName fromSHScene:(NSString*)shScene;

-(void) playAnimation;
-(void) pauseAnimation;
-(void) restartAnimation;
-(void) stopAnimation; //removes the animation entirely

-(bool) isAnimationPaused;

-(NSString*) animationName;
-(int) numberOfFrames;
-(int) currentFrame;

-(float) animationDelayPerUnit;
-(void) setAnimationDelayPerUnit:(float)d;

-(float)animationDuration;//return how much time will take for a loop to complete

-(void)setFrame:(int)frmNo;
-(void) nextFrame;
-(void) prevFrame;

-(void) nextFrameAndRepeat; //will loop when it reaches end
-(void) prevFrameAndRepeat; //will loop when it reaches start

-(bool) isAtLastFrame;
////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////


//CLASS METHODS
//------------------------------------------------------------------------------
+(NSString*) uniqueNameForBody:(b2Body*)body;
+(LHSprite*) spriteForBody:(b2Body*)body;
+(int) tagForBody:(b2Body*)body;
+(bool) isLHSprite:(id)object;

//SORTING
//------------------------------------------------------------------------------
- (NSComparisonResult)sortAscending:(LHSprite *)other;
- (NSComparisonResult)sortDescending:(LHSprite *)other;

//COLLISION FILTERING
//------------------------------------------------------------------------------
-(void)setCollisionFilterCategory:(int)category;
-(void)setCollisionFilterMask:(int)mask;
-(void)setCollisionFilterGroup:(int)group;

//TYPE CONVERSION
//------------------------------------------------------------------------------
-(void)makeDynamic;
-(void)makeStatic;
-(void)makeKinematic;


//SH help methods
-(void)setShSceneName:(NSString *)sceneName;
@end	
